Revert 2a967faadf76. It broke the following:
given the IL
------------------------------------------------------
declare arm_aapcscc i32 @nacl_dyncode_copy()
define arm_aapcscc void @test_loading_large_chunk(i8* %x ) nounwind {
entry:
  %t2 = alloca [131072 x i8], align 1
  call arm_aapcscc  i32 @nacl_dyncode_copy() nounwind
  call arm_aapcscc  i32 @memcmp(i8* %x, i8* null, i32 131072) nounwind readonly
  ret void
}
declare arm_aapcscc i32 @memcmp(i8* nocapture, i8* nocapture, i32) nounwind
readonly
---------------------------------------------------

The command

llc -sfi-cp-fudge -sfi-cp-fudge-percent=80 -sfi-store -sfi-stack -sfi-branch
-sfi-data -no-inline-jumptables -march=arm -mcpu=arm1156t2f-s
-mtriple=armv6-*-*eabi* -arm-reserve-r9 -f test.bc -o test.s

will produce the following instruction:

str     d15, [sp, #+4]

which causes the assembler to complain

Error: ARM register expected

I verified that reverting this change fixes the problem. With this in we can
find a better fix for the original problem.